# code: language=ansible

---

- name: "Nginx | Repositories | Dnf / Yum | GPG Keys"
  ansible.builtin.rpm_key:
    key: "{{ item.key }}"
    state: present
  with_items: "{{ nginx_repositories[nginx_branch]['dnf'] }}"
  when:
    - nginx_repositories | is_ne_dict
    - nginx_branch in nginx_repositories
    - '"dnf" in nginx_repositories[nginx_branch]'
    - item.key is defined
  become: true
  tags:
    - nginx
    - nginx-repositories

- name: "Common | Repositories | Dnf / Yum | Add repository"
  ansible.builtin.template:
    src: "repositories/dnf.repo.j2"
    dest: "/etc/yum.repos.d/{{ item.name }}.repo"
    owner: "root"
    group: "root"
    mode: "0644"
    backup: false
  with_items: "{{ nginx_repositories[nginx_branch]['dnf'] }}"
  when:
    - nginx_repositories | is_ne_dict
    - nginx_branch in nginx_repositories
    - '"dnf" in nginx_repositories[nginx_branch]'
  notify:
    - Update dnf cache
  become: true
  tags:
    - nginx
    - nginx-repositories

- name: "Nginx | Repositories | Dnf / Yum | Flush handlers"
  ansible.builtin.meta: flush_handlers
  tags:
    - nginx
    - nginx-repositories
